./cirTest -F ./tests.script/do1 &> ./output/do1
./cirTest -F ./tests.script/do1a &> ./output/do1a
./cirTest -F ./tests.script/do2 &> ./output/do2
./cirTest -F ./tests.script/do3 &> ./output/do3
./cirTest -F ./tests.script/do4 &> ./output/do4
./cirTest -F ./tests.script/do5 &> ./output/do5
./cirTest -F ./tests.script/do6 &> ./output/do6
./cirTest -F ./tests.script/do7 &> ./output/do7
./cirTest -F ./tests.script/do8 &> ./output/do8
./cirTest -F ./tests.script/do9 &> ./output/do9
./cirTest -F ./tests.script/do10 &> ./output/do10
./cirTest -F ./tests.script/do11 &> ./output/do11
